"""empty message

Revision ID: 0b968468cfad
Revises: cf1bd7c12f07
Create Date: 2022-10-17 16:24:30.044753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b968468cfad'
down_revision = 'cf1bd7c12f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('file_show_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_notebooks_file_show_name'), 'notebooks', ['file_show_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebooks_file_show_name'), table_name='notebooks')
    op.drop_column('notebooks', 'file_show_name')
    # ### end Alembic commands ###
