"""empty message

Revision ID: 7cd087f466bf
Revises: 6e90104c5458
Create Date: 2022-10-16 21:11:07.371557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd087f466bf'
down_revision = '6e90104c5458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_filename'), 'notebooks', ['filename'], unique=True)
    op.create_index(op.f('ix_notebooks_image'), 'notebooks', ['image'], unique=True)
    op.create_index(op.f('ix_notebooks_timestamp'), 'notebooks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebooks_timestamp'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_image'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_filename'), table_name='notebooks')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
